# -*- coding: utf-8 -*-
"""Aastha PDM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dtwWqoia9gyya5WtnUnVbMBgKXYcoedE

# **Loading the Necessary Datasets**
"""

# ==========================================================
# IMPORTING ALL REQUIRED LIBRARIES
# Student Dropout Prediction - Random Forest & Bagging Model
# ==========================================================


# -------------------------------
# Data Processing Libraries
# -------------------------------

import pandas as pd
import numpy as np


# -------------------------------
# Data Visualisation Libraries
# -------------------------------

import matplotlib.pyplot as plt
import seaborn as sns


# -------------------------------
# Data Preparation Libraries
# -------------------------------

from sklearn.model_selection import train_test_split

from sklearn.preprocessing import StandardScaler


# -------------------------------
# Machine Learning Models
# -------------------------------

from sklearn.ensemble import (
    RandomForestClassifier,
    BaggingClassifier
)

from sklearn.tree import DecisionTreeClassifier


# -------------------------------
# Model Evaluation Metrics
# -------------------------------

from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix,
    log_loss,
    roc_auc_score,
    roc_curve
)


# -------------------------------
# Warning Management
# -------------------------------

import warnings

warnings.filterwarnings("ignore")


# -------------------------------
# Visualisation Configuration
# -------------------------------

sns.set_style("whitegrid")

"""# **Dataset Loading Steps**"""

# ==========================================
# Loading Student Datasets
# ==========================================

# Loading academic and personal information
student_df = pd.read_excel("/content/personal_data.xlsx")

# Loading VLE engagement information
vle_df = pd.read_csv("/content/vle_data.csv")

"""# **Combine Both Datasets**"""

# ==========================================
# Combining datasets using ID
# ==========================================

combined_df = pd.merge(
    student_df,
    vle_df,
    on="id",
    how="inner"
)


combined_df.head()

print("Combined Dataset Shape:", combined_df.shape)

"""## **Check Missing Values**"""

combined_df.isnull().sum()

# ==========================================
# Duplicate Analysis
# ==========================================

duplicate_records = combined_df.duplicated().sum()

print("Number of Duplicate Records:", duplicate_records)

# ==========================================
# Statistical Overview
# ==========================================

combined_df.describe()

"""# **EXPLORATORY DATA ANALYSIS (EDA)**"""

# Replace abbreviations with full labels
combined_df['gender'] = combined_df['gender'].replace({
    'F': 'Female',
    'M': 'Male'
})

# ==========================================
# Gender Based Dropout Calculation
# ==========================================

gender_analysis = (
    combined_df
    .groupby("gender")["dropout_risk"]
    .value_counts()
    .unstack()
)


gender_analysis

"""# **OUTLIER ANALYSIS — Attendance Rate**"""

# ==========================================
# Attendance Outlier Detection
# ==========================================

plt.figure(figsize=(10,6))


sns.boxplot(
    x=combined_df["attendance_rate"],
    color="#06d6a0"
)


plt.title(
    "Outlier Detection in Attendance Rate"
)


plt.show()

"""# **Descriptive Statistics**

## **Dropout Data Divided by Gender**
"""

# ============================================
# Gender-wise dropout analysis
# ============================================

gender_dropout = pd.crosstab(
    combined_df['gender'],
    combined_df['dropout_risk']
)

gender_dropout.columns = [
    "Completed Students",
    "Dropped Students"
]

gender_dropout

# ============================================
# Gender dropout visualization
# ============================================

ax = gender_dropout.plot(
    kind='bar',
    figsize=(11,6),
    color=['#118AB2','#EF476F']
)


plt.title(
    "Student Completion and Dropout Status by Gender",
    fontsize=14
)

plt.xlabel("Gender")

plt.ylabel("Number of Students")


for container in ax.containers:
    ax.bar_label(container)


plt.xticks(rotation=0)

plt.legend()

plt.show()

"""## **Average Age of Students**"""

# ============================================
# Average age calculation
# ============================================

mean_age = combined_df['age'].agg(['mean','min','max'])

mean_age

plt.figure(figsize=(10,5))


sns.kdeplot(
    combined_df['age'],
    fill=True,
    color="#06D6A0"
)


plt.title(
    "Age Distribution of Students"
)

plt.xlabel("Student Age")

plt.ylabel("Density")


plt.show()

"""# **Average Minutes on VLE per Week**"""

# ============================================
# VLE engagement statistics
# ============================================

vle_summary = combined_df[
    'minutes_on_vle_per_week'
].describe()


vle_summary

plt.figure(figsize=(10,6))


sns.histplot(
    combined_df['minutes_on_vle_per_week'],
    bins=25,
    color="#8338EC"
)


plt.title(
    "Weekly VLE Engagement Distribution"
)

plt.xlabel(
    "Minutes Spent on VLE Weekly"
)

plt.ylabel(
    "Student Count"
)


plt.show()

"""# **Distribution of Attendance Rate**"""

# ============================================
# Attendance calculation
# ============================================

attendance_statistics = combined_df[
    'attendance_rate'
].agg(
    ['mean','median','std']
)


attendance_statistics

plt.figure(figsize=(10,6))


sns.histplot(
    combined_df['attendance_rate'],
    bins=20,
    kde=True,
    color="#FF9F1C"
)


plt.axvline(
    combined_df['attendance_rate'].mean(),
    color='black',
    linestyle='--',
    label="Average Attendance"
)


plt.title(
    "Distribution of Attendance Rate"
)

plt.xlabel(
    "Attendance Percentage"
)

plt.ylabel(
    "Frequency"
)


plt.legend()

plt.show()

"""# **Distribution of Assignment Grade**"""

# ============================================
# Assignment grade analysis
# ============================================

grade_statistics = combined_df[
    'avg_assignment_grade'
].agg(
    ['mean','median','min','max']
)


grade_statistics

plt.figure(figsize=(10,6))


sns.histplot(
    combined_df['avg_assignment_grade'],
    bins=25,
    kde=True,
    color="#FF006E"
)


plt.title(
    "Distribution of Average Assignment Grades"
)

plt.xlabel(
    "Average Assignment Grade"
)

plt.ylabel(
    "Number of Students"
)


plt.show()

"""# **Attendance Rate by Accommodation Type**"""

# ============================================
# Accommodation attendance comparison
# ============================================

attendance_accommodation = (
    combined_df
    .groupby('accommodation_type')
    ['attendance_rate']
    .mean()
    .sort_values()
)


attendance_accommodation

bars = plt.bar(
    attendance_accommodation.index,
    attendance_accommodation.values,
    color=[
        '#00B4D8',
        '#90BE6D',
        '#F94144'
    ]
)


plt.title(
    "Average Attendance Rate by Accommodation Type"
)


plt.xlabel(
    "Accommodation Type"
)


plt.ylabel(
    "Average Attendance"
)


plt.bar_label(
    bars,
    fmt="%.2f"
)


plt.xticks(rotation=25)


plt.show()

"""# **Relationship Between Commuting Distance and Dropout**"""

# ============================================
# Distance and dropout relationship
# ============================================

distance_dropout = (
    combined_df
    .groupby('dropout_risk')
    ['commuting_distance_km']
    .mean()
)


distance_dropout

plt.figure(figsize=(8,6))


sns.boxplot(
    x='dropout_risk',
    y='commuting_distance_km',
    data=combined_df,
    palette=['#4CC9F0','#F72585']
)


plt.title(
    "Commuting Distance Impact on Dropout Risk"
)


plt.xlabel(
    "Dropout Status"
)


plt.ylabel(
    "Distance to Campus (KM)"
)


plt.xticks(
    [0,1],
    ['Completed','Dropped Out']
)


plt.show()

"""# **Dropout Numbers by Accommodation Type**"""

# ============================================
# Dropout count by accommodation
# ============================================

accommodation_dropout = (
    combined_df[
        combined_df['dropout_risk']==1
    ]
    .groupby('accommodation_type')
    .size()
)


accommodation_dropout

plt.figure(figsize=(8,6))


bars = plt.bar(
    accommodation_dropout.index,
    accommodation_dropout.values,
    color=[
        '#7209B7',
        '#3A0CA3',
        '#4361EE'
    ]
)


plt.title(
    "Dropout Numbers by Accommodation Type"
)


plt.xlabel(
    "Accommodation Type"
)


plt.ylabel(
    "Number of Dropouts"
)


plt.bar_label(
    bars
)


plt.xticks(rotation=25)


plt.show()

"""# **Relationship Between Assignment Grade and Late Submissions**"""

# ============================================
# Correlation analysis
# ============================================

assignment_late_relation = combined_df[
    [
        'avg_assignment_grade',
        'late_submissions'
    ]
].corr()


assignment_late_relation

plt.figure(figsize=(8,6))


sns.scatterplot(
    data=combined_df,
    x='late_submissions',
    y='avg_assignment_grade',
    color="#2A9D8F",
    s=70
)


plt.title(
    "Relationship Between Late Submissions and Assignment Grade"
)


plt.xlabel(
    "Number of Late Submissions"
)


plt.ylabel(
    "Average Assignment Grade"
)


plt.show()

"""# **Correlation Heatmap**"""

plt.figure(figsize=(12,7))


numeric_data = combined_df.select_dtypes(
    include=np.number
)


sns.heatmap(
    numeric_data.corr(),
    annot=True,
    cmap="Spectral",
    fmt=".2f"
)


plt.title(
    "Correlation Analysis of Student Variables"
)


plt.show()

"""# **Define Features and Target Variable**"""

# ==========================================
# Feature and Target Separation
# ==========================================

X = combined_df.drop(
    'dropout_risk',
    axis=1
)


y = combined_df['dropout_risk']


print("Feature Shape:", X.shape)

print("Target Shape:", y.shape)

"""# **Convert Categorical Variables**"""

# ==========================================
# Encoding categorical features
# ==========================================

categorical_features = X.select_dtypes(
    include=['object']
).columns


print(
    "Categorical Columns:",
    list(categorical_features)
)

# One-hot encoding

X_encoded = pd.get_dummies(
    X,
    columns=categorical_features,
    drop_first=True
)


print(
    "Encoded Dataset Shape:",
    X_encoded.shape
)

"""# **Train Test Split**"""

# ==========================================
# Splitting dataset
# ==========================================

X_train, X_test, y_train, y_test = train_test_split(
    X_encoded,
    y,
    test_size=0.2,
    random_state=25,
    stratify=y
)


print(
    "Training Data:",
    X_train.shape
)


print(
    "Testing Data:",
    X_test.shape
)

"""# **Feature Scaling**"""

# ==========================================
# Feature Scaling
# ==========================================

scaler = StandardScaler()


X_train_scaled = scaler.fit_transform(
    X_train
)


X_test_scaled = scaler.transform(
    X_test
)


print("Scaling completed")

"""# **Train Random Forest Model**"""

# ==========================================
# Random Forest Training
# ==========================================

rf_model = RandomForestClassifier(
    n_estimators=150,
    max_depth=8,
    random_state=25
)


rf_model.fit(
    X_train,
    y_train
)

"""# **Random Forest Prediction**"""

# ==========================================
# Predictions
# ==========================================

rf_prediction = rf_model.predict(
    X_test
)


rf_probability = rf_model.predict_proba(
    X_test
)[:,1]

"""# **Random Forest Accuracy**"""

# ==========================================
# Accuracy Score
# ==========================================

rf_accuracy = accuracy_score(
    y_test,
    rf_prediction
)


print(
    "Random Forest Accuracy:",
    round(rf_accuracy,4)
)

"""# **Random Forest Classification Report**"""

# ==========================================
# Classification Report
# ==========================================

print(
    classification_report(
        y_test,
        rf_prediction
    )
)

"""# **Random Forest Log Loss**"""

# ==========================================
# Log Loss Calculation
# ==========================================

rf_logloss = log_loss(
    y_test,
    rf_probability
)


print(
    "Random Forest Log Loss:",
    round(rf_logloss,4)
)

"""# **Random Forest Confusion Matrix**"""

# ==========================================
# Confusion Matrix
# ==========================================

rf_cm = confusion_matrix(
    y_test,
    rf_prediction
)


plt.figure(figsize=(6,5))


sns.heatmap(
    rf_cm,
    annot=True,
    fmt='d',
    cmap="RdPu"
)


plt.title(
    "Random Forest Confusion Matrix"
)


plt.xlabel(
    "Predicted Label"
)


plt.ylabel(
    "Actual Label"
)


plt.show()

"""# **Random Forest ROC-AUC Curve**"""

# ==========================================
# ROC-AUC Curve
# ==========================================

rf_fpr, rf_tpr, threshold = roc_curve(
    y_test,
    rf_probability
)


rf_auc = roc_auc_score(
    y_test,
    rf_probability
)


plt.figure(figsize=(7,5))


plt.plot(
    rf_fpr,
    rf_tpr,
    label=f"Random Forest AUC = {rf_auc:.3f}",
    color="#2A9D8F"
)


plt.plot(
    [0,1],
    [0,1],
    linestyle="--",
    color="grey"
)


plt.title(
    "ROC Curve - Random Forest"
)


plt.xlabel(
    "False Positive Rate"
)


plt.ylabel(
    "True Positive Rate"
)


plt.legend()

plt.show()

"""# **Train Bagging Model**"""

# ==========================================
# Bagging Classifier Training
# ==========================================

bag_model = BaggingClassifier(
    estimator=DecisionTreeClassifier(),
    n_estimators=100,
    random_state=25
)


bag_model.fit(
    X_train,
    y_train
)

"""# **Bagging Predictions**"""

# ==========================================
# Bagging Predictions
# ==========================================

bag_prediction = bag_model.predict(
    X_test
)


bag_probability = bag_model.predict_proba(
    X_test
)[:,1]

"""# **Bagging Accuracy Score**"""

# ==========================================
# Accuracy
# ==========================================

bag_accuracy = accuracy_score(
    y_test,
    bag_prediction
)


print(
    "Bagging Accuracy:",
    round(bag_accuracy,4)
)

"""# **Bagging Classification Report**"""

# ==========================================
# Classification Report
# ==========================================

print(
    classification_report(
        y_test,
        bag_prediction
    )
)

"""# **Bagging Log Loss**"""

# ==========================================
# Log Loss
# ==========================================

bag_logloss = log_loss(
    y_test,
    bag_probability
)


print(
    "Bagging Log Loss:",
    round(bag_logloss,4)
)

"""# **Bagging Confusion Matrix**"""

# ==========================================
# Confusion Matrix
# ==========================================

bag_cm = confusion_matrix(
    y_test,
    bag_prediction
)


plt.figure(figsize=(6,5))


sns.heatmap(
    bag_cm,
    annot=True,
    fmt='d',
    cmap="RdBu"
)


plt.title(
    "Bagging Classifier Confusion Matrix"
)


plt.xlabel(
    "Predicted Label"
)


plt.ylabel(
    "Actual Label"
)


plt.show()

"""# **Bagging ROC-AUC Curve**"""

# ==========================================
# ROC Curve
# ==========================================

bag_fpr, bag_tpr, threshold = roc_curve(
    y_test,
    bag_probability
)


bag_auc = roc_auc_score(
    y_test,
    bag_probability
)


plt.figure(figsize=(7,5))


plt.plot(
    bag_fpr,
    bag_tpr,
    label=f"Bagging AUC = {bag_auc:.3f}",
    color="#8338EC"
)


plt.plot(
    [0,1],
    [0,1],
    linestyle="--",
    color="grey"
)


plt.title(
    "ROC Curve - Bagging Classifier"
)


plt.xlabel(
    "False Positive Rate"
)


plt.ylabel(
    "True Positive Rate"
)


plt.legend()

plt.show()

"""# **Final Model Comparison Table**"""

# ==========================================
# Model Performance Comparison
# ==========================================

model_results = pd.DataFrame({

    "Model":[
        "Random Forest",
        "Bagging Classifier"
    ],

    "Accuracy":[
        rf_accuracy,
        bag_accuracy
    ],

    "Log Loss":[
        rf_logloss,
        bag_logloss
    ],

    "ROC-AUC":[
        rf_auc,
        bag_auc
    ]

})


model_results